version: '3.8' 

services:
  load-balancer:
    build: .  
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=root123
      - DB_NAME=balancerdb
    depends_on:
      - db

  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: root123  
      POSTGRES_DB: balancerdb 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: