listen_port: "8080"
algorithm: "round-robin" # "round-robin" || "least-connections" || "random" 
rate_limit:
  capacity: 100    
  refill_per_sec: 10
backends:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
health_check:
  interval: "10s"
  timeout: "2s"